config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  devise_for :users
  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  get 'pages/about'

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, ImageUploader

  searchkick

  has_many :reviews

  validates :name, :address, :phone, :website, :image, presence: true
  validates :phone, format: {with:    /\A\(\d{3}\) \d{3}-\d{4}\z/,
                             message: 'must be in the format (123) 456-7890'}
  validates :website, format: {with:    /\Ahttps?:\/\/.*\z/,
                               message: 'must start with http:// or https://'}
  validates :address, format: {with:    /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
                               message: 'must be in the format 350 Fifth Avenue, New York, NY 10118'}
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]

  def search
    @restaurants = if params[:search].present?
      Restaurant.search(params[:search])
                   else
      Restaurant.all
                   end
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    # Accesses foreign-key from set_restaurant method
    @reviews = Review.where(restaurant_id: @restaurant.id).order('created_at DESC')
    @avg_rating = if @reviews.blank?
      0
                  else
      @reviews.average(:rating).round(2)
                  end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit; end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
  end

  # Only admins can modify Restaurant data
  def check_user
  unless current_user.admin?
    redirect_to root_url, alert: 'Sorry, only admins can do that!'
  end
end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true, :html => { multipart: true }) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
     <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name, class: "form-control", placeholder: "Panera" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address, class: "form-control", placeholder: "201 Brookline Avenue, Boston, MA 02215" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :restaurant_phone, class: "form-control", placeholder: "(617) 247-0174" %>
  </div>

  <div class="form-group">
    <%= form.label :website %>
    <%= form.text_field :website, id: :restaurant_website, class: "form-control", placeholder: "http://www.panerabread.com/" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :restaurant_image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<div class ="jumbotron">
  <h2>Yelpdemo is the best way to find reviews on local restaurants.</h2>
  <h3>Explore the favorite diners, pastry shops, and eateries in your community.
  <br>Leave reviews and ratings for your fellow foodies.</h3>
</div> 

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link" %>
<% end %>

<%= image_tag "https://s3.us-east-2.amazonaws.com/yelpdemo-july-2017/buildings.png" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag @restaurant.image_url %>

    <h2>
      <%= @restaurant.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div> 
    <p><%= "#{@reviews.length} reviews" %></p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @restaurant.website, @restaurant.website %>
    </p>

    <%= link_to "Write Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
    <iframe width="230"
      height="230"
      frameborder="0" style="border:0" src="//www.google.com/maps/embed/v1/place?q=<%= @restaurant.address.parameterize %>
      &zoom=14
      &key=AIzaSyBMGX9yGasG2OJTz5WkRNf8kqoEPfFZdus">
    </iframe>
  </div>

  <br>
  <br>

  
   
  <div class="col-md-9">
    <% if @reviews.blank? %>
      <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>

      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <h4>
                  <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                </h4>
                <p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
              </td>
              <td>
                <div class="star-rating" data-score= <%= review.rating %> ></div>
                <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
                  <% if user_signed_in? %>
                  <% if (review.user == current_user) || (current_user.admin?) %>
                    <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review) %>
                    <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% end %>
  </div>
</div>

<script>
  $('.star-rating').raty({
    path: 'https://s3.us-east-2.amazonaws.com/yelpdemo-july-2017/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>